id: 76829fd650f54e29ada66d4edead9483
initial_creation_type: ocr
source_metadata:
  volumes:
    bcff02a8c15548bbb2e41f4f516f5cb5:
      base_file: v061.txt
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      volume_number: 62
